# Generated by Django 4.2.3 on 2023-08-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('delivery_date', models.DateField()),
                ('is_delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Deliver',
        ),
    ]
